export const SEED_USTALAR = [
  { id: 'u1', ad: 'Hasan Yıldız',  uzmanlik: 'Kaynak',  baslangic: '2019-04-12' },
  { id: 'u2', ad: 'Mehmet Akçay',  uzmanlik: 'Tesisat', baslangic: '2021-09-03' },
  { id: 'u3', ad: 'İbrahim Demir', uzmanlik: 'Kaynak',  baslangic: '2018-02-18' },
  { id: 'u4', ad: 'Yusuf Kara',    uzmanlik: 'Montaj',  baslangic: '2022-11-25' },
  { id: 'u5', ad: 'Ali Çelik',     uzmanlik: 'Boya',    baslangic: '2020-06-30' },
];

export const SEED_BORU_FITTINGS = [
  { id: 'bf-001', tur: 'Boru',   cap: '1"', cins: 'Siyah',     stok: 84, birim: 'm',    minimum: 20 },
  { id: 'bf-002', tur: 'Dirsek', cap: '1"', cins: 'Siyah',     stok: 36, birim: 'adet', minimum: 10 },
  { id: 'bf-003', tur: 'Tee',    cap: '1"', cins: 'Siyah',     stok: 18, birim: 'adet', minimum: 8 },
  { id: 'bf-004', tur: 'Manşon', cap: '1"', cins: 'Siyah',     stok: 24, birim: 'adet', minimum: 10 },
  { id: 'bf-005', tur: 'Boru',   cap: '2"', cins: 'Siyah',     stok: 42, birim: 'm',    minimum: 20 },
  { id: 'bf-006', tur: 'Dirsek', cap: '2"', cins: 'Siyah',     stok: 9,  birim: 'adet', minimum: 10 },
  { id: 'bf-007', tur: 'Tee',    cap: '2"', cins: 'Siyah',     stok: 11, birim: 'adet', minimum: 6 },
  { id: 'bf-008', tur: 'Manşon', cap: '2"', cins: 'Siyah',     stok: 14, birim: 'adet', minimum: 8 },
  { id: 'bf-009', tur: 'Boru',   cap: '3"', cins: 'Siyah',     stok: 18, birim: 'm',    minimum: 12 },
  { id: 'bf-010', tur: 'Dirsek', cap: '3"', cins: 'Siyah',     stok: 6,  birim: 'adet', minimum: 6 },
  { id: 'bf-011', tur: 'Boru',   cap: '1"', cins: 'Galvaniz',  stok: 60, birim: 'm',    minimum: 20 },
  { id: 'bf-012', tur: 'Dirsek', cap: '1"', cins: 'Galvaniz',  stok: 22, birim: 'adet', minimum: 8 },
  { id: 'bf-013', tur: 'Tee',    cap: '1"', cins: 'Galvaniz',  stok: 12, birim: 'adet', minimum: 6 },
  { id: 'bf-014', tur: 'Manşon', cap: '1"', cins: 'Galvaniz',  stok: 4,  birim: 'adet', minimum: 8 },
  { id: 'bf-015', tur: 'Boru',   cap: '2"', cins: 'Galvaniz',  stok: 31, birim: 'm',    minimum: 18 },
  { id: 'bf-016', tur: 'Dirsek', cap: '2"', cins: 'Galvaniz',  stok: 14, birim: 'adet', minimum: 8 },
  { id: 'bf-017', tur: 'Boru',   cap: '1"', cins: 'Paslanmaz', stok: 22, birim: 'm',    minimum: 12 },
  { id: 'bf-018', tur: 'Dirsek', cap: '1"', cins: 'Paslanmaz', stok: 8,  birim: 'adet', minimum: 6 },
  { id: 'bf-019', tur: 'Tee',    cap: '1"', cins: 'Paslanmaz', stok: 3,  birim: 'adet', minimum: 4 },
  { id: 'bf-020', tur: 'Boru',   cap: '2"', cins: 'Paslanmaz', stok: 12, birim: 'm',    minimum: 8 },
];

export const SEED_DIGER_MALZEME = [
  { id: 'dm-01', kategori: 'Elektrod', ad: 'Rutil Elektrod Ø2.5',   stok: 14,  birim: 'paket', minimum: 6 },
  { id: 'dm-02', kategori: 'Elektrod', ad: 'Rutil Elektrod Ø3.2',   stok: 9,   birim: 'paket', minimum: 6 },
  { id: 'dm-03', kategori: 'Elektrod', ad: 'Bazik Elektrod Ø2.5',   stok: 5,   birim: 'paket', minimum: 4 },
  { id: 'dm-04', kategori: 'Elektrod', ad: 'Bazik Elektrod Ø3.2',   stok: 3,   birim: 'paket', minimum: 4 },
  { id: 'dm-05', kategori: 'Boya',     ad: 'Antipas Boya — Gri',    stok: 18,  birim: 'litre', minimum: 10 },
  { id: 'dm-06', kategori: 'Boya',     ad: 'Antipas Boya — Kırmızı', stok: 7,  birim: 'litre', minimum: 8 },
  { id: 'dm-07', kategori: 'Bağlantı', ad: 'M12 Cıvata',            stok: 240, birim: 'adet',  minimum: 80 },
  { id: 'dm-08', kategori: 'Bağlantı', ad: 'M12 Rod',               stok: 32,  birim: 'adet',  minimum: 20 },
];

export const SEED_HAREKETLER = [
  { id: 'h-001', malzemeId: 'bf-002', tip: 'gelis',    miktar: 50, tarih: '2026-04-22', not: 'Tedarikçi: Demir Yapı', fis: 'F-2026-441' },
  { id: 'h-002', malzemeId: 'bf-002', tip: 'kullanim', miktar: 8,  tarih: '2026-05-02', ustaId: 'u2', is: 'Bodrum kat ısıtma hattı — kazan dairesi bağlantısı' },
  { id: 'h-003', malzemeId: 'bf-002', tip: 'kullanim', miktar: 6,  tarih: '2026-05-09', ustaId: 'u1', is: '4. kat radyatör hattı dönüş kolları' },
  { id: 'h-004', malzemeId: 'bf-005', tip: 'gelis',    miktar: 60, tarih: '2026-04-18', not: 'Tedarikçi: Borsan', fis: 'F-2026-438' },
  { id: 'h-005', malzemeId: 'bf-005', tip: 'kullanim', miktar: 12, tarih: '2026-05-06', ustaId: 'u3', is: 'Kazan dairesi ana kollektör' },
  { id: 'h-006', malzemeId: 'bf-005', tip: 'kullanim', miktar: 6,  tarih: '2026-05-12', ustaId: 'u3', is: 'Pompa bağlantı hattı' },
  { id: 'h-007', malzemeId: 'bf-006', tip: 'kullanim', miktar: 4,  tarih: '2026-05-11', ustaId: 'u1', is: 'Çatı katı manifold' },
  { id: 'h-008', malzemeId: 'bf-014', tip: 'kullanim', miktar: 6,  tarih: '2026-05-10', ustaId: 'u2', is: 'Mutfak temiz su hattı ek noktaları' },
  { id: 'h-009', malzemeId: 'bf-019', tip: 'kullanim', miktar: 2,  tarih: '2026-05-13', ustaId: 'u3', is: 'Endüstriyel mutfak — fritöz hattı' },
  { id: 'h-010', malzemeId: 'dm-04',  tip: 'gelis',    miktar: 6,  tarih: '2026-04-29', not: 'Tedarikçi: Kaynak Market', fis: 'F-2026-452' },
  { id: 'h-011', malzemeId: 'dm-04',  tip: 'kullanim', miktar: 2,  tarih: '2026-05-07', ustaId: 'u1', is: '3" Siyah boru kaynağı — kazan dairesi' },
  { id: 'h-012', malzemeId: 'dm-04',  tip: 'kullanim', miktar: 1,  tarih: '2026-05-14', ustaId: 'u3', is: 'Paslanmaz tee kaynak işçiliği' },
  { id: 'h-013', malzemeId: 'dm-06',  tip: 'kullanim', miktar: 4,  tarih: '2026-05-04', ustaId: 'u5', is: 'Ana kollektör ve çelik konstrüksiyon astar' },
  { id: 'h-014', malzemeId: 'dm-06',  tip: 'kullanim', miktar: 3,  tarih: '2026-05-13', ustaId: 'u5', is: 'Çatı kirişleri 2. kat astar boyası' },
  { id: 'h-015', malzemeId: 'dm-07',  tip: 'gelis',    miktar: 200, tarih: '2026-04-15', not: 'Tedarikçi: Çelik Vida', fis: 'F-2026-430' },
  { id: 'h-016', malzemeId: 'dm-07',  tip: 'kullanim', miktar: 32, tarih: '2026-05-05', ustaId: 'u4', is: 'Ana taşıyıcı flanş bağlantıları' },
  { id: 'h-017', malzemeId: 'dm-07',  tip: 'kullanim', miktar: 16, tarih: '2026-05-11', ustaId: 'u4', is: 'Pompa montaj plakası' },
  { id: 'h-018', malzemeId: 'dm-01',  tip: 'gelis',    miktar: 10, tarih: '2026-04-20', not: 'Tedarikçi: Kaynak Market', fis: 'F-2026-444' },
  { id: 'h-019', malzemeId: 'dm-01',  tip: 'kullanim', miktar: 2,  tarih: '2026-05-08', ustaId: 'u1', is: '1" galvaniz dirsek kaynakları' },
  { id: 'h-020', malzemeId: 'bf-008', tip: 'kullanim', miktar: 4,  tarih: '2026-05-12', ustaId: 'u2', is: 'Kollektör ara bağlantıları' },
];
